version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: biblioteca_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    logging:
      driver: none

  api:
    build: .
    container_name: biblioteca_api
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/biblioteca_digital
    depends_on:
      - mongodb
    volumes:
      - ./src:/app/src

volumes:
  mongodb_data:
